# Generated by Django 5.1.4 on 2024-12-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='tmdb_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
