# Generated by Django 5.1.4 on 2024-12-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_viewedmovie_viewedseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(default='Resumen no disponible.'),
            preserve_default=False,
        ),
    ]
