# Generated by Django 5.1.4 on 2024-12-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='tmdb_id',
        ),
        migrations.AlterField(
            model_name='series',
            name='poster_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
