# Generated by Django 5.1.4 on 2024-12-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_series_tmdb_id_alter_series_poster_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='tmdb_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
