# Generated by Django 5.1.4 on 2024-12-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_series_tmdb_id_alter_series_poster_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='tmdb_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
