# Generated by Django 5.1.4 on 2024-12-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_viewedmovie_liked_viewedseries_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
